---

- name: Install Cryptomunitions.
  become: yes
  apt:
    state: present
    name: '{{ helga_ssl_packages }}'

- name: Install Python Cryptomunitions
  pip:
    name: service_identity
    version: 16.0.0
    virtualenv: '{{ helga_home }}'
