---

- name: Install supervisord.
  become: yes
  apt: name=supervisor state=present

- name: Install supervisor conf.
  become: true
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/helga.conf

- name: Install supervisor process.
  become: yes
  supervisorctl: name=helga state=present

- name: Restart supervisor process.
  become: yes
  supervisorctl: name=helga state=restarted
